spring:
  profiles:
    active: smart
  mvc:
    format:
      date: yyyy-MM-dd
  jpa:
    hibernate:
      show-sql: true
      dll-auto: update
      use-new-id-generator-mappings: false


  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/hr_database
    username: springuser
    password: passwd
    driver-class-name: com.mysql.jdbc.Driver

hr:
  salary:
    default.payrisepercent: 5
    smart.payrisepercents: 10,5,2,0
    smart.yearsspentlimits: 10,5,2.5


